# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ref_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_refSettingsForm(object):
    def setupUi(self, refSettingsForm):
        refSettingsForm.setObjectName("refSettingsForm")
        refSettingsForm.resize(453, 311)
        self.verticalLayout = QtWidgets.QVBoxLayout(refSettingsForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.colorMapGroupBox = QtWidgets.QGroupBox(refSettingsForm)
        self.colorMapGroupBox.setObjectName("colorMapGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.colorMapGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.colorMapGroupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.colorMapGroupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.maxLineEdit = QtWidgets.QLineEdit(self.colorMapGroupBox)
        self.maxLineEdit.setObjectName("maxLineEdit")
        self.gridLayout.addWidget(self.maxLineEdit, 2, 2, 1, 1)
        self.minLineEdit = QtWidgets.QLineEdit(self.colorMapGroupBox)
        self.minLineEdit.setObjectName("minLineEdit")
        self.gridLayout.addWidget(self.minLineEdit, 0, 2, 1, 1)
        self.autosetCheckBox = QtWidgets.QCheckBox(self.colorMapGroupBox)
        self.autosetCheckBox.setObjectName("autosetCheckBox")
        self.gridLayout.addWidget(self.autosetCheckBox, 3, 2, 1, 1)
        self.normalizeCheckBox = QtWidgets.QCheckBox(self.colorMapGroupBox)
        self.normalizeCheckBox.setObjectName("normalizeCheckBox")
        self.gridLayout.addWidget(self.normalizeCheckBox, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.colorMapGroupBox)
        self.orientationGroupBox = QtWidgets.QGroupBox(refSettingsForm)
        self.orientationGroupBox.setObjectName("orientationGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.orientationGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.orientationComboBox = QtWidgets.QComboBox(self.orientationGroupBox)
        self.orientationComboBox.setObjectName("orientationComboBox")
        self.orientationComboBox.addItem("")
        self.orientationComboBox.addItem("")
        self.orientationComboBox.addItem("")
        self.orientationComboBox.addItem("")
        self.orientationComboBox.addItem("")
        self.orientationComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.orientationComboBox)
        self.verticalLayout.addWidget(self.orientationGroupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(refSettingsForm)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(refSettingsForm)
        QtCore.QMetaObject.connectSlotsByName(refSettingsForm)

    def retranslateUi(self, refSettingsForm):
        _translate = QtCore.QCoreApplication.translate
        refSettingsForm.setWindowTitle(_translate("refSettingsForm", "Reference settings"))
        self.colorMapGroupBox.setTitle(_translate("refSettingsForm", "Color map"))
        self.label_2.setText(_translate("refSettingsForm", "Max"))
        self.label.setText(_translate("refSettingsForm", "Min"))
        self.autosetCheckBox.setText(_translate("refSettingsForm", "Autoset levels"))
        self.normalizeCheckBox.setText(_translate("refSettingsForm", "Normalize"))
        self.orientationGroupBox.setTitle(_translate("refSettingsForm", "Orientation"))
        self.orientationComboBox.setItemText(0, _translate("refSettingsForm", "None"))
        self.orientationComboBox.setItemText(1, _translate("refSettingsForm", "90deg"))
        self.orientationComboBox.setItemText(2, _translate("refSettingsForm", "180deg"))
        self.orientationComboBox.setItemText(3, _translate("refSettingsForm", "270deg"))
        self.orientationComboBox.setItemText(4, _translate("refSettingsForm", "Flip H"))
        self.orientationComboBox.setItemText(5, _translate("refSettingsForm", "Flip V"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    refSettingsForm = QtWidgets.QWidget()
    ui = Ui_refSettingsForm()
    ui.setupUi(refSettingsForm)
    refSettingsForm.show()
    sys.exit(app.exec_())
